abbr ga 'git add'
abbr gb 'git branch'
abbr gbl 'git blame'
abbr gcm 'git commit -m'
abbr gco 'git checkout'
abbr gd 'git diff'
abbr gf 'git fetch'
abbr gl 'git log'
abbr gm 'git merge'
abbr gps 'git push'
abbr gpl 'git pull'
abbr grb 'git rebase'
abbr gst 'git status'
